import { jsPDF } from 'jspdf';
import type { Priority } from '@/components/accessibility-fix-priority-engine/types';

const PAGE_MARGIN = 18;
const SECTION_GAP = 8;

const brand = {
  ink: '#0b1828',
  muted: '#64748b',
  accent: '#7dca2f',
  soft: '#e2e8f0',
};

const wrapText = (doc: jsPDF, text: string, maxWidth: number) =>
  doc.splitTextToSize(text, maxWidth);

const drawSectionDivider = (doc: jsPDF, y: number) => {
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(PAGE_MARGIN, y, 210 - PAGE_MARGIN, y);
};

export function generatePDFSummary(priorities: Priority[]): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - PAGE_MARGIN * 2;
  let cursorY = 22;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(brand.ink);
  doc.text('Accessibility Fix Priority Summary', PAGE_MARGIN, cursorY);
  cursorY += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(brand.muted);
  doc.text('Generated by Seego Design • Accessibility Fix Priority Engine', PAGE_MARGIN, cursorY);
  cursorY += SECTION_GAP;

  drawSectionDivider(doc, cursorY);
  cursorY += SECTION_GAP;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(brand.ink);
  doc.text('Your Top 3 Priorities', PAGE_MARGIN, cursorY);
  cursorY += SECTION_GAP;

  priorities.forEach((priority, index) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(brand.ink);
    doc.text(`${index + 1}. ${priority.title}`, PAGE_MARGIN, cursorY);
    cursorY += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(brand.muted);
    doc.text(`Impact: ${priority.impact} • Effort: ${priority.effort}`, PAGE_MARGIN, cursorY);
    cursorY += 5;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10.5);
    doc.setTextColor(brand.ink);
    const whyLines = wrapText(doc, priority.why, contentWidth);
    doc.text(whyLines, PAGE_MARGIN, cursorY);
    cursorY += whyLines.length * 4.5 + 2;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(brand.ink);
    doc.text('Recommended actions:', PAGE_MARGIN, cursorY);
    cursorY += 4.5;

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(brand.muted);
    priority.actions.forEach((item) => {
      const lines = wrapText(doc, `• ${item}`, contentWidth);
      doc.text(lines, PAGE_MARGIN, cursorY);
      cursorY += lines.length * 4.2;
    });

    cursorY += SECTION_GAP;

    if (cursorY > 260 && index < priorities.length - 1) {
      doc.addPage();
      cursorY = 20;
    }
  });

  drawSectionDivider(doc, cursorY);
  cursorY += SECTION_GAP;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(brand.ink);
  doc.text('Next Steps', PAGE_MARGIN, cursorY);
  cursorY += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10.5);
  doc.setTextColor(brand.ink);
  const steps = [
    'Assign owners to each priority and set a remediation timeline',
    'Retest fixes with keyboard + screen readers',
    'Document evidence for legal and compliance teams',
    'Schedule follow-up monitoring to prevent regressions',
  ];
  steps.forEach((item, index) => {
    doc.text(`${index + 1}. ${item}`, PAGE_MARGIN, cursorY);
    cursorY += 5;
  });

  cursorY += 6;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setTextColor(brand.ink);
  const ctaLines = wrapText(
    doc,
    'Need help fixing these? Ideliver accessibility audits, remediation sprints, and compliance documentation.',
    contentWidth,
  );
  doc.text(ctaLines, PAGE_MARGIN, cursorY);

  doc.save('accessibility-fix-priorities.pdf');
}
