import { jsPDF } from 'jspdf';
import type { AppDecisionResults } from '@/components/app-decision-tool-engine/utils/scoring';

const PAGE_MARGIN = 18;
const SECTION_GAP = 8;

const brand = {
  ink: '#0b1828',
  muted: '#64748b',
  accent: '#7dca2f',
  soft: '#e2e8f0',
};

const wrapText = (doc: jsPDF, text: string, maxWidth: number) =>
  doc.splitTextToSize(text, maxWidth);

const drawSectionDivider = (doc: jsPDF, y: number) => {
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(PAGE_MARGIN, y, 210 - PAGE_MARGIN, y);
};

export function generateAppDecisionPDF(results: AppDecisionResults): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - PAGE_MARGIN * 2;
  let cursorY = 22;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(brand.ink);
  doc.text('App Decision Tool Summary', PAGE_MARGIN, cursorY);
  cursorY += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(brand.muted);
  doc.text('Generated by Seego Design - App Decision Tool', PAGE_MARGIN, cursorY);
  cursorY += SECTION_GAP;

  drawSectionDivider(doc, cursorY);
  cursorY += SECTION_GAP;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(brand.ink);
  doc.text('App Overview', PAGE_MARGIN, cursorY);
  cursorY += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10.5);
  doc.setTextColor(brand.ink);
  const summaryLines = wrapText(doc, results.summary, contentWidth);
  doc.text(summaryLines, PAGE_MARGIN, cursorY);
  cursorY += summaryLines.length * 4.5 + 4;

  drawSectionDivider(doc, cursorY);
  cursorY += SECTION_GAP;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(brand.ink);
  doc.text('Scores', PAGE_MARGIN, cursorY);
  cursorY += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10.5);
  doc.setTextColor(brand.muted);
  doc.text(`App Readiness Score: ${results.readinessScore}/100`, PAGE_MARGIN, cursorY);
  cursorY += 5;
  doc.text(`Complexity Tier: ${results.complexityTier}`, PAGE_MARGIN, cursorY);
  cursorY += SECTION_GAP;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(brand.ink);
  doc.text('Key Risks & Blind Spots', PAGE_MARGIN, cursorY);
  cursorY += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10.5);
  doc.setTextColor(brand.muted);
  results.riskFlags.forEach((risk) => {
    const riskLines = wrapText(doc, `- ${risk}`, contentWidth);
    doc.text(riskLines, PAGE_MARGIN, cursorY);
    cursorY += riskLines.length * 4.2;
  });
  cursorY += 4;

  drawSectionDivider(doc, cursorY);
  cursorY += SECTION_GAP;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(brand.ink);
  doc.text('Recommended Action Plan', PAGE_MARGIN, cursorY);
  cursorY += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10.5);
  doc.setTextColor(brand.ink);
  const steps = [
    `Recommended next step: ${results.recommendedNextStep}`,
    'Lock the core action and supporting screens.',
    'Confirm budget, timeline, and platform priorities.',
    'Prototype or validate with 5-8 target users before full build.',
  ];
  steps.forEach((step, index) => {
    doc.text(`${index + 1}. ${step}`, PAGE_MARGIN, cursorY);
    cursorY += 5;
  });

  cursorY += SECTION_GAP;
  drawSectionDivider(doc, cursorY);
  cursorY += SECTION_GAP;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(brand.ink);
  doc.text('If You Ignore This...', PAGE_MARGIN, cursorY);
  cursorY += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10.5);
  doc.setTextColor(brand.muted);
  const consequences = [
    'Budget burn from building features that users will not adopt.',
    'Launch delays caused by unclear scope and platform sprawl.',
    'Hard-to-fix rework after real users reveal the missing core flow.',
  ];
  consequences.forEach((item) => {
    const lines = wrapText(doc, `- ${item}`, contentWidth);
    doc.text(lines, PAGE_MARGIN, cursorY);
    cursorY += lines.length * 4.2;
  });

  cursorY += 6;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setTextColor(brand.ink);
  const ctaLines = wrapText(
    doc,
    'If you want this done for you, Ican scope the MVP, prototype the core flow, and deliver a build plan tied to your budget.',
    contentWidth,
  );
  doc.text(ctaLines, PAGE_MARGIN, cursorY);

  doc.save('app-decision-tool-summary.pdf');
}
